name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 44.207.2.250  # Your EC2 instance public IP
  APP_DIR: /home/ubuntu  # Define the app directory as an environment variable
  DOCKERHUB_USERNAME: lavanyaarora08  # Replace with your DockerHub username
  DOCKERHUB_REPO_CATALOG: lavanyaarora08/07-netflix-movie-catalog  # DockerHub repository for the Netflix Catalog service
  DOCKERHUB_REPO_FRONTEND: lavanyaarora08/08-netflix-frontend  # DockerHub repository for the Netflix Frontend service
  IMAGE_TAG: latest  # You can set it dynamically using Git SHA or another method if needed

jobs:
  Deploy:
    name: Deploy to EC2 and DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
            - name: Build Docker images for catalog and frontend services
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_FRONTEND:$IMAGE_TAG ./08-netflix-frontend
      - name: Push Docker images to DockerHub
        run: |
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_CATALOG:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_FRONTEND:$IMAGE_TAG

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > mykey.pem
          chmod 600 mykey.pem

      - name: Create app directory on EC2
        run: |
          ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "mkdir -p $APP_DIR"

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i mykey.pem -r ./* ubuntu@$EC2_PUBLIC_IP:$APP_DIR

      - name: Verify copied files on EC2
        run: |
          ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "ls -R $APP_DIR"

      - name: Execute deploy script on EC2
        run: |
          ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "cd $APP_DIR && bash deploy.sh"
